version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hrsurvey_postgres
    environment:
      POSTGRES_DB: hrsurvey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hrsurvey_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrsurvey_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/hrsurvey
      SECRET_KEY: your-super-secret-jwt-key-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - hrsurvey_network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrsurvey_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hrsurvey_network

volumes:
  postgres_data:

networks:
  hrsurvey_network:
    driver: bridge