services:
  postgres:
    image: postgres:15-alpine
    container_name: hrsurvey_postgres
    environment:
      POSTGRES_DB: hrsurvey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nigielove_21
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hrsurvey_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrsurvey_backend
    environment:
      DATABASE_URL: postgresql://postgres:Nigielove_21@postgres:5432/hrsurvey
      SECRET_KEY: your-super-secret-jwt-key-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - hrsurvey_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrsurvey_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000 # Use container name for networking
    networks:
      - hrsurvey_network

volumes:
  postgres_data:

networks:
  hrsurvey_network:
    driver: bridge