version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: hrsurvey_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Changed from 543 to 5433 to match CI/CD
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hrsurvey_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrsurvey_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: 7075  # Internal port for backend
    ports:
      - "7075:7075"  # External:Internal
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - hrsurvey_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrsurvey_frontend
    ports:
      - "8088:3000"  # External:Internal
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:7075  # Updated to use backend port
    networks:
      - hrsurvey_network

volumes:
  postgres_data:

networks:
  hrsurvey_network:
    driver: bridge